### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Daktyl198** [jsoctocat/BDO-Launcher#24]
With the change from EAC to Xigncode, BDO now runs on Linux, and has only a few issues left. One is the auction house not loading properly, and unfortunately the other is the launcher rendering as a black screen. The launcher _functions_, patching and all buttons work, but finding those buttons is near impossible.

If you could make a native Linux build of the project somehow (porting it to a newer .NET version) it would be greatly appreciated.

For what it's worth, the current version of the application seems to work properly under Proton, this would just be a quality of life change, though I know how much work it would take.

**Comment by jsoctocat** [comment]
yeah the big obstacle would be having to understand how PA fetch/verify/patch/repair the game files, I don't think I can dedicate that much time and effort for this project, I do have a steam deck so I can try and get this to work with linux, I will take a look at it this weekend.

as for the auction house issue, I don't remember exactly, but I think it's because linux has this weird connection that blocks certain things, not 100% sure on this though.

**Comment by Daktyl198** [comment]
The launcher and auction house issues are 100% just issues with Proton itself. I wouldn't bother yourself too much with that, except to maybe keep your launcher open when updating the game via the official client, to inform the user (who can't see the progress bar) when the game is fully updated, rather than downloading the game files yourself.

Updating your launcher to a newer .NET version (and finding a platform-agnostic UI library) would still be a lot of work however, so I'm not really expecting it. This was just a hopeful request lol.

**Comment by jsoctocat** [comment]
which version of the .NET are you referring to?

**Comment by jsoctocat** [comment]
I don't think porting the launcher to .net 8.0 is worth the effort since you will still need to use proton to run the game as the game isn't built for linux, also the new anticheat is closing in the game for failing the heartbeat check.

**Comment by AkechiShiro** [comment]
I don't think this launcher will be necessary since the launcher issue has been fixed for Black Desert Online in Wine, it was fixed a few hours ago, the fix hasn't landed in a release just yet and is a bit hacky, see https://github.com/ValveSoftware/Proton/issues/3620#issuecomment-1902687136

**Comment by facundoveliz** [comment]
It actually works for linux, if anyone wan'ts to play before the realease of Proton, just throw the files and execute with Steam, the Experimental version worked well.

**Comment by jsoctocat** [comment]
> It actually works for linux, if anyone wan'ts to play before the realease of Proton, just throw the files and execute with Steam, the Experimental version worked well.
> 
> More info [here](https://forums.lutris.net/t/xigncode3-black-desert-online/19816/2).

are you able to run the game for more than 10 mins? I have tried this on my steam deck, this launcher can start the game but the game will close for failing the xigncode's heartbeat check for me

**Comment by facundoveliz** [comment]
> > It actually works for linux, if anyone wan'ts to play before the realease of Proton, just throw the files and execute with Steam, the Experimental version worked well.
> > More info [here](https://forums.lutris.net/t/xigncode3-black-desert-online/19816/2).
> 
> are you able to run the game for more than 10 mins? I have tried this on my steam deck, this launcher can start the game but the game will close for failing the xigncode's heartbeat check for me

Current session is 16mins and no problems.

![2024-01-22_17-02](https://github.com/jsoctocat/BDO-Launcher/assets/68577124/e9ac2143-437a-4b68-948d-809970040f14)

**Comment by jsoctocat** [comment]
Just an update, this launcher will not be able to support Linux natively, because none of the open source Chromium Embedded Framework works on Linux, CefSharp only works for windows as it's visual c++, CefGlue only works for windows and OSX, I have ran into CefNet, even though, it's possible to grab the NuGet package but that repo no longer exist and I can hardly find any documentation on how to use it.

I did however manage to recreate the launcher in NET 8.0, I will keep the files on my computer until a cef for linux pops up in the future.

And as I stated before, even if this launcher manage to support Linux natively, the developer still need to build the game to support Linux as well otherwise you will still need to run proton one way or another.

**Comment by Daktyl198** [comment]
That’s entirely valid. Impressive that you recreated it in .net 8 so fast.

As for Proton, I have no issues using it. The game will never be Linux native. I just wanted this launcher Linux native to make it easier to install/use. The game’s issues (including the launcher) have all been fixed already in Proton Experimental, but I actually use your launcher on Windows. That’s why I thought of it as a potential fix for the Linux issues lol.

As mentioned in the first post, your launcher’s current version already works under Proton, it’s just mildly annoying to set up lol.

**Comment by jsoctocat** [comment]
Release [2.0.0](https://github.com/jsoctocat/BDO-Launcher/releases/tag/2.0.0) now supports Linux, tested it on Nobara

**Comment by Daktyl198** [comment]
> Release [2.0.0](https://github.com/jsoctocat/BDO-Launcher/releases/tag/2.0.0) now supports Linux, tested it on Nobara

Thanks for the hard work! I noticed that in the release notes, you suggest downloading .NET Runtime 8. On .NET 6+ (if I remember correctly) apps are compiled as "self contained" by default, meaning that dotnet will include the necessary runtime pieces into the final build/release folder of your application. Users no longer have to download a separate runtime.

There's also an experimental "single exe" option to build the entire solution into a single executable. See here: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview

**Comment by jsoctocat** [comment]
I didn't know that, thanks for letting me know, self contained option only show up on publish mode, there is the runtime folder so I am not sure if that's what this is but since I have the SDK installed I don't have any issues from my end. When I ran the launcher on Linux it prompted me to install .NET 8.0 runtime though, so there is that.

**Comment by Daktyl198** [comment]
Interestingly, I get 2 separate errors on my Arch setup. Using your distributed binaries, I get a permission error when it tries to start Firefox
```
 ╭─daktyl@daktyl in ~/Downloads/bdolauncher as 🧙 took 4ms
 ╰─λ ./Launcher.Desktop
Unhandled exception. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/home/daktyl/Downloads/bdolauncher/.playwright/node/linux-x64/node' with working directory '/home/daktyl/Downloads/bdolauncher'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.Playwright.Transport.StdIOTransport.StartProcessWithUTF8IOEncoding(Process process) in /_/src/Playwright/Transport/StdIOTransport.cs:line 168
   at Microsoft.Playwright.Transport.StdIOTransport..ctor() in /_/src/Playwright/Transport/StdIOTransport.cs:line 47
   at Microsoft.Playwright.Playwright.CreateAsync() in /_/src/Playwright/Playwright.cs:line 44
   at Launcher.ViewModels.MainViewModel.MainForm_Load(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Launcher.Desktop.Program.Main(String[] args)
Aborted (core dumped)
```

But when I try building from the source myself (and copying the firefox folder into the .playwright folder of my build) using `dotnet publish Launcher.Desktop --os=linux --self-contained` I get a completely separate error about it not being able to find Firefox in the first place, since it's looking for firefox.exe:

```
 ╭─daktyl@daktyl in ~/Downloads/BDO-Launcher-2.0.0/Launcher.Desktop/bin/Release/net8.0/linux-x64/publish as 🧙 took 7ms
 ╰─λ ./Launcher.Desktop
Unhandled exception. Microsoft.Playwright.PlaywrightException: Failed to launch firefox because executable doesn't exist at /home/daktyl/Downloads/BDO-Launcher-2.0.0/Launcher.Desktop/bin/Release/net8.0/linux-x64/publish/\.playwright\firefox-1438\firefox\firefox.exe
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 207
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 537
   at Microsoft.Playwright.Core.BrowserType.LaunchPersistentContextAsync(String userDataDir, BrowserTypeLaunchPersistentContextOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 154
   at Launcher.ViewModels.MainViewModel.MainForm_Load(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Launcher.Desktop.Program.Main(String[] args)
Aborted (core dumped)
```

And indeed, your binary does prompt me to install the dotnet runtime, but I tested it and apparently using the `--self-contained` flag during the publishing step removes that requirement. Not sure why it's not doing it by default with your project.

As an aside, .desktop files on Linux are a special kind of file, so having the file name be `Launcher.Desktop` means there's an extra step or two required to run the executable as a program (at least from a GUI) rather than having it try to open it as a text file. Not sure if there's really anything you can do to fix that on Linux specifically since I'm not super familiar with multi-os build configurations in dotnet.

**Comment by jsoctocat** [comment]
Error 1: the launcher, node, and firefox must mark as executable. Right click, edit property. Or, chmod +x.

Error 2: It's detecting your system not as Linux so its routing the calls for else which is what it's doing on windows, which is why it's trying to find firefox.exe rather than firefox 

it's not self contained because I built the project rather than publish it, self contain is an option only when publishing.

It's. desktop because it's how Avalonia handles cross platforms by default

**Comment by Daktyl198** [comment]
I can confirm that  manually marking node and firefox executable fixes the first error. This lets me get far enough to see the project seems to be hardcoded to expect Proton-GE 8.30. I'm currently using the bleeding edge version of Proton Experiemental. Requiring Proton-GE is fine, but it's probably best to mention it somewhere. Currently the application just closes when it runs the proton command, and doesn't check to see if the command actually worked.

New issue I've found:
- after saving my login data, subsequent openings of the program cut off a few characters of my password, requiring me to re-enter my password every time.

And the BSA doesn't work, but that's a Proton-GE issue. Everything else I did in the game seemed to work okay. I don't have OTP turned on currently so I haven't tested that yet. And of course it'd be nice if the node and firefox executables were marked properly prior to distribution.

**Comment by jsoctocat** [comment]
check the front page

I double checked and this is indeed an issue

I can't check this issue right now

I will try to fix them tonight after work

**Comment by jsoctocat** [comment]
I have fixed the password issue and added feedback to when otp window's login button is clicked (this change is not in release).

as for the issue of using a different proton, you have to use the launch option, again, refer to main page.

playwright does not support self contain nor single executable, so this is it, all the other options do not work or cause memory leak, playwright has to fix it for it to work refer to [this issue on playwright repo](https://github.com/microsoft/playwright-dotnet/issues/2255)

**Comment by jsoctocat** [comment]
Release [2.0.2](https://github.com/jsoctocat/BDO-Launcher/releases/tag/2.0.2) Fixed the issue where in game browser doesn't work (dice game, guild page, wiki page, etc)

This ticket is now considered complete
