### ISSUE TITLE
After Press start game Launcher Closed but game not launched

### ISSUE THREAD

**Issue by ManchiSoul** [jsoctocat/BDO-Launcher#29]
Hello

when i press start game, it took 10 seconds then launcher close. but the game did not launched

There is no error output showing to my screen.

I checked windows reporting problem center and here is what i just found
```
Source
Launcher.Windows

Summary
Stopped working

Date
‎3/‎7/‎2024 7:54 AM

Status
Report sent

Description
Faulting Application Path:	E:\Games\BDO Launcher\Launcher.Windows.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	Launcher.Windows.exe
Application Version:	1.0.0.0
Application Timestamp:	65680000
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.19041.3996
Fault Module Timestamp:	b756c9ff
Exception Code:	e0434352
Exception Offset:	000000000002cf19
OS Version:	10.0.19044.2.0.0.256.191
Locale ID:	1033
Additional Information 1:	4b11
Additional Information 2:	4b11b578910323ba1481d2d8d0440474
Additional Information 3:	7a99
Additional Information 4:	7a99093d7640db09df5b0f71bd95e9ec

Extra information about the problem
Bucket ID:	a970710e79daf0514a915513ce91d52f (1914404860167574831)
```

Here is another debug from event viewer

.NET runtime

```
Application: Launcher.Windows.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TimeoutException: Timeout 30000ms exceeded while waiting for event "Response"
 ---> System.TimeoutException: Timeout 30000ms exceeded while waiting for event "Response"
   at Microsoft.Playwright.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0() in /_/src/Playwright/Helpers/TaskHelper.cs:line 73
   at Microsoft.Playwright.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in /_/src/Playwright/Helpers/TaskHelper.cs:line 109
   at Microsoft.Playwright.Core.Waiter.WaitForPromiseAsync[T](Task`1 task, Action dispose) in /_/src/Playwright/Core/Waiter.cs:line 220
   --- End of inner exception stack trace ---
   at Microsoft.Playwright.Core.Waiter.WaitForPromiseAsync[T](Task`1 task, Action dispose) in /_/src/Playwright/Core/Waiter.cs:line 228
   at Microsoft.Playwright.Core.Page.InnerWaitForEventAsync[T](PlaywrightEvent`1 pageEvent, Func`1 action, Func`2 predicate, Nullable`1 timeout) in /_/src/Playwright/Core/Page.cs:line 484
   at Launcher.Source.AuthenticationServiceProvider.CheckErrorMsg(IPage page, String javascript, String step)
   at Launcher.Source.AuthenticationServiceProvider.AuthenticateAsync(IBrowserContext browser, String username, String password, String region, Boolean useOtp, Boolean useMasterOtp, String otp)
   at Launcher.ViewModels.MainViewModel.StartGameAsync(Boolean useMasterOtp, String otpNotMaster)
   at Launcher.ViewModels.MainViewModel.GameStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Launcher.Windows.Program.Main(String[] args)
```
Here is gif i made showing the behavior of the launcher 

![Launcher Windows_odnUkMnkam](https://github.com/jsoctocat/BDO-Launcher/assets/45339747/936341db-5eef-4a95-9135-ba87050476bb)

I tried to select debug mode but it open a new browser window and nothing showing up

**Comment by jsoctocat** [comment]
turn on debug mode then start the game, let me know where it gets stuck, from the error it's showing you are at least able to get to the login page?

**Comment by ManchiSoul** [comment]
> turn on debug mode then start the game, let me know where it gets stuck, from the error it's showing you are at least able to get to the login page?

Is there a path where those debug mode register?

**Comment by jsoctocat** [comment]
it's the right option above start game, turn it on then restart the launcher, then start the game, it should show you the login process that typically runs in the backend

**Comment by ManchiSoul** [comment]
> it's the right option above start game, turn it on then restart the launcher, then start the game, it should show you the login process that typically runs in the backend

Here is the spot that stopped during login process in debug mode

![firefox_8Vu55IWGmm](https://github.com/jsoctocat/BDO-Launcher/assets/45339747/b47b2099-7dcf-4700-9d63-1e489ae9b026)

**Comment by jsoctocat** [comment]
ah I ran into this issue this morning and I planned to fix it lol

I am in the process of testing my changes and will be pushing a build soon, for now click on "confirm" manually to process to the next step

**Comment by ManchiSoul** [comment]
ty @jsoctocat for confirming this bug. yea i pressed confirm and it worked fine. i am gonna wait for next build

**Comment by jsoctocat** [comment]
Try out release [2.0.3](https://github.com/jsoctocat/BDO-Launcher/releases/tag/2.0.3) and let me know if it fixes this issue, not exactly sure why this happens because most of the time the whole process is smooth, hate running into odd issues that cannot be reproduced 100% of the time.

**Comment by ManchiSoul** [comment]
> Try out release [2.0.3](https://github.com/jsoctocat/BDO-Launcher/releases/tag/2.0.3) and let me know if it fixes this issue, not exactly sure why this happens because most of the time the whole process is smooth, hate running into odd issues that cannot be reproduced 100% of the time.

it work perfectly with debug mode checked. if i tried with unchecked debug mode option. it wont work

I tried 5 times to make sure it wont randomly work.

**Comment by jsoctocat** [comment]
could you post the log of why it crashed from event viewer? without debug mode it simply don't render the process...

**Comment by ManchiSoul** [comment]
@jsoctocat  After bdo launcher closed. the event viewer registered 3 logs

1st log 
Level : Information
Source : Windows Error Reporting
```
Fault bucket 1914404860167574831, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Launcher.Windows.exe
P2: 1.0.0.0
P3: 65680000
P4: KERNELBASE.dll
P5: 10.0.19041.3996
P6: b756c9ff
P7: e0434352
P8: 000000000002cf19
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD81C.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDC82.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDC93.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDCA1.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERDCC1.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Launcher.Windows_f0d4ed462e5cc7a5c28e7cc217debdf4c37d8059_29d2eca8_1a786a37-6206-4033-b8a4-db674d4cbc48

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0e17ccc1-a36f-4a9c-a98e-813cedde6acb
Report Status: 268435456
Hashed bucket: a970710e79daf0514a915513ce91d52f
Cab Guid: 0
```

2nd Log
Level: Error 
Source : Application Error
```
Faulting application name: Launcher.Windows.exe, version: 1.0.0.0, time stamp: 0x65680000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3996, time stamp: 0xb756c9ff
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x1264
Faulting application start time: 0x01da70a12c01edf1
Faulting application path: E:\Games\BDO Launcher\Launcher.Windows.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 0e17ccc1-a36f-4a9c-a98e-813cedde6acb
Faulting package full name: 
Faulting package-relative application ID:
```


3rd log
Level: Error
Source: .NET Runtime
```Application: Launcher.Windows.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Playwright.TargetClosedException: Target page, context or browser has been closed
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 207
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 537
   at Microsoft.Playwright.Core.BrowserContext.NewPageAsync() in /_/src/Playwright/Core/BrowserContext.cs:line 445
   at Launcher.Source.AuthenticationServiceProvider.AuthenticateAsync(IBrowserContext browser, String username, String password, String region, Boolean useOtp, Boolean useMasterOtp, String otp)
   at Launcher.ViewModels.MainViewModel.StartGameAsync(Boolean useMasterOtp, String otpNotMaster)
   at Launcher.ViewModels.MainViewModel.GameStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Launcher.Windows.Program.Main(String[] args)```

**Comment by jsoctocat** [comment]
you are now getting a different issue than before, you are crashing before reaching the otp state, I will check it later tonight

**Comment by jsoctocat** [comment]
alright I managed on only reproduce this bug only when debug mode is turned on and I close the browser then start the game.

if you do not want a browser to show up you have to uncheck the debug mode and then restart the launcher, if the browser is terminated manually then the whole process will fail because there is no session to start the login process.

**Comment by ManchiSoul** [comment]
> alright I managed on only reproduce this bug only when debug mode is turned on and I close the browser then start the game.
> 
> if you do not want a browser to show up you have to uncheck the debug mode and then restart the launcher, if the browser is terminated manually then the whole process will fail because there is no session to start the login process.

I can confirm this. I had to uncheck debug mode option and restart the launcher. it works well. but doing it without restart the launcher will not work. but its a better way around than nothing

Thank @jsoctocat
