### ISSUE TITLE
Unhandled Exception in 1.1.0c 

### ISSUE THREAD

**Issue by moeffju** [jsoctocat/BDO-Launcher#4]
Upgraded to 1.1.0c, including modules, overwriting all files. Launcher window comes up, then after a delay of 3-5s, a .NET exception is thrown:

```
************** Exception Text **************
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Launcher.AuthenticationServiceProvider.<AuthenticateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Launcher.MainForm.<StartGameAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Launcher.MainForm.<GameStart>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

This might be due to the servers still being down for maintenance, but that case should also be handled (more) gracefully.

**Comment by moeffju** [comment]
After maintenance period is over, the launcher starts and shows an empty alert box with an OK button. Nothing further happens on dismissing the box.

**Comment by jsoctocat** [comment]
Sounds like an issue with requesting the play token, however, I cannot reproduce the issue described, seems to be an issue that only happens during the game maintenance, therefore, I will look into it during the next maintenance.

**Comment by jsoctocat** [comment]
As for your 2nd comment, the issue with the launcher starts and shows an empty alert box, that's caused by a racing issue, I'm working on the fix now, but as for the unexpected json issue, I will have to wait until the maintenance starts to see what's causing it.

**Comment by jsoctocat** [comment]
version 1.1.1 added the maintenance check and better handling for the Json error
