### ISSUE TITLE
Intermittent launch errors

### ISSUE THREAD

**Issue by moeffju** [jsoctocat/BDO-Launcher#6]
Starting the launcher, first got a timeout after 9000ms, next launch this happened. Assuming it is related to the general server slowness that is currently going on.

```
************** Exception Text **************
System.Exception: Unable to execute javascript at this time, scripts can only be executed within a V8Context. Use the IWebBrowser.CanExecuteJavascriptInMainFrame property to guard against this exception. See https://github.com/cefsharp/CefSharp/wiki/General-Usage#when-can-i-start-executing-javascript for more details on when you can execute javascript. For frames that do not contain Javascript then no V8Context will be created. Executing a script once the frame has loaded it's possible to create a V8Context. You can use browser.GetMainFrame().ExecuteJavaScriptAsync(script) or browser.GetMainFrame().EvaluateScriptAsync to bypass these checks (advanced users only).
   at CefSharp.WebBrowserExtensions.ThrowExceptionIfCanExecuteJavascriptInMainFrameFalse()
   at CefSharp.WebBrowserExtensions.EvaluateScriptAsync(IWebBrowser browser, String script, Nullable`1 timeout, Boolean useImmediatelyInvokedFuncExpression)
   at Launcher.AuthenticationServiceProvider.<CheckErrorMsg>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Launcher.AuthenticationServiceProvider.<AuthenticateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Launcher.MainForm.<StartGameAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Launcher.MainForm.<GameStart>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by jsoctocat** [comment]
yes, this issue is caused by the general server slowness from PA but the bug can be ironed out, I will look into it.

**Comment by jsoctocat** [comment]
version 1.1.3 should address this issue, feel free to open up this issue if doesn't.

**Comment by jsoctocat** [comment]
I can't seem to fix this issue lol, gonna work on it today

**Comment by jsoctocat** [comment]
1.1.4 should address this issue
